security:
    encoders:
        UserBundle\Entity\Player: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: main
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            anonymous:    true
            remember_me:
                secret:     %secret%

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/select, role: ROLE_USER }
        - { path: ^/play, role: ROLE_USER }
        - { path: ^/defis, role: ROLE_USER }
        - { path: ^/duel, role: ROLE_USER }
        - { path: ^/result, role: ROLE_USER }
        - { path: ^/player, role: ROLE_USER }
        - { path: ^/category/, role: ROLE_ADMIN }
        - { path: ^/questioneasy, role: ROLE_ADMIN }
        - { path: ^/questionmedium, role: ROLE_ADMIN }
        - { path: ^/questionhard, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

