<?php

namespace QuizzBundle\Repository;

/**
 * QuestionEasyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionEasyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategory($category) {
        $rawSql = "SELECT * FROM category JOIN question_easy ON category.id=question_easy.category_id WHERE category.id=$category";

        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
        $stmt->execute([]);

        return $stmt->fetchAll();
    }

}
