<?php

namespace QuizzBundle\Repository;

/**
 * QuestionEasyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionEasyRepository extends \Doctrine\ORM\EntityRepository
{
}
