<?php

namespace QuizzBundle\Repository;

/**
 * QuestionMediumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionMediumRepository extends \Doctrine\ORM\EntityRepository
{
}
