<?php

namespace QuizzBundle\Repository;

/**
 * QuestionHardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionHardRepository extends \Doctrine\ORM\EntityRepository
{
}
